version: 2

models:
  - name: dim_corpo_employee
    description: "This table contains detailed information about corporate employees, including their personal details and organizational affiliations."

    columns:
      - name: user_id
        description: "A unique identifier for each employee."
        tests:
          - unique
          - not_null
      - name: first_name
      - name: last_name
      - name: email
        description: "The email address of the employee, used for communication."
      - name: phone_number
      - name: organisation_id
        description: "A unique identifier for the organization the employee belongs to."
      - name: organisation_name
      - name: pricing_plan
        description: "The subscription pricing plan associated with the employee's organization."
      - name: subscribed_at
        description: "The timestamp indicating when the employee's organization subscribed to the service."


  - name: fact_corpo_subscription_income
    description: "This table tracks monthly subscription income generated by corporate organizations."

    columns:
      - name: month
        description: "The month for which the income is recorded (format: YYYY-MM)."
      - name: organisation_id
      - name: organisation_name
      - name: income
        description: "The total income generated by the organization for the given month."
      - name: pricing_plan


  - name: fact_income_monthly
    description: "This table aggregates monthly income data, categorized by product type."

    columns:
      - name: month
        description: "The month for which the income is aggregated (format: YYYY-MM)."
      - name: product_type
        description: "The type of product or service generating the income (e.g., TRAVEL_CAR, TRAVEL_HOTEL, CORPO_SUBSCRIPTION)."
      - name: income


  - name: fact_travel_car_booking
    description: "This table records details of car rental bookings made through the travel platform."

    columns:
      - name: booking_reference
        description: "A unique reference number for the car rental booking."
      - name: booked_at
      - name: start_date
      - name: end_date
      - name: booking_status
      - name: booking_price
      - name: commission_percentage
        description: "The percentage of the booking price retained as commission."
      - name: organisation_id
      - name: organisation_name
      - name: user_id
      - name: car_rental_company_id
      - name: car_rental_company_name
      - name: car_model_name
      - name: payment_done_at


  - name: fact_travel_hotel_booking
    description: "This table records details of hotel bookings made through the travel platform."

    columns:
      - name: booking_reference
        description: "A unique reference number for the hotel booking."
      - name: booked_at
      - name: start_date
      - name: end_date
      - name: booking_status
      - name: booking_price
      - name: commission_percentage
        description: "The percentage of the booking price retained as commission."
      - name: organisation_id
      - name: organisation_name
      - name: user_id
      - name: hotel_id
      - name: hotel_name
      - name: hotel_room_id
      - name: payment_done_at


  - name: fact_travel_income
    description: "This table tracks daily income generated from travel-related products and services."

    columns:
      - name: day
        description: "The date for which the income is recorded (format: YYYY-MM-DD)."
      - name: product_type
        description: "The type of product or service generating the income (e.g., TRAVEL_CAR, TRAVEL_HOTEL)."
      - name: income
      - name: organisation_id
      - name: organisation_name